apiVersion: v1
kind: ReplicationController
metadata:
  name: alpha-qe-cassandra-rc
spec:
  replicas: 0
  # selector identifies the set of Pods that this
  # replicaController is responsible for managing
  selector:
    name: cassandra
    env: alpha
  # podTemplate defines the 'cookie cutter' used for creating
  # new pods when necessary
  template:
    metadata:
      labels:
        # Important: these labels need to match the selector above
        # The api server enforces this constraint.
        name: cassandra
        env: alpha
    spec:
      containers:
        - name: cassandra
          image: cassandra:2.2
          command:
            - bash
            - "-c"
            - "sed -i 's/^start_rpc.*$/start_rpc: true/' /etc/cassandra/cassandra.yaml; /docker-entrypoint.sh -f"
          ports:
            # https://wiki.apache.org/cassandra/FAQ#ports
            containerPort: 9042
            #  name: cql
            #- containerPort: 7000
            - containerPort: 9160
              name: thrift
          #env:
            #- name: CASSANDRA_LISTEN_ADDRESS
              #value: 127.0.0.1

