apiVersion: v1
kind: Service
metadata:
  labels:
    name: cassandra
    env: alpha
  name: cassandra
spec:
  type: "NodePort"
  ports:
    - port: 80
      targetPort: 9042
  selector:
    name: cassandra
    env: alpha
