apiVersion: v1beta3
kind: ReplicationController
metadata:
  name: hawkular-restci-controller1
spec:
  replicas: 1
  # selector identifies the set of Pods that this
  # replicaController is responsible for managing
  selector:
    name: hawkular
    env: qe1
  # podTemplate defines the 'cookie cutter' used for creating
  # new pods when necessary
  template:
    metadata:
      labels:
        # Important: these labels need to match the selector above
        # The api server enforces this constraint.
        name: hawkular
        env: qe1 
    spec:
      containers:
        - name: hawkular
          image: hawkular/hawkular:latest
          resources:
            limits:
              cpu: 2
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            # length of time to wait for a pod to initialize
            # after pod startup, before applying health checking
            initialDelaySeconds: 480
            timeoutSeconds: 10
