apiVersion: v1
kind: Service
metadata:
  labels:
    name: hawkular
    env: demo
  name: hawkular
spec:
  type: "NodePort"
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30085
  selector:
    name: hawkular
    env: snapshot
