apiVersion: v1beta3
kind: Service
metadata:
  labels:
    name: hawkular
    env: snapshot
  name: hawkular
spec:
  type: NodePort
  ports:
    - port: 18080
      targetPort: 8080
  selector:
    name: hawkular
    env: snapshot
  publicIPs:
    - 172.18.17.27
