apiVersion: v1
kind: ReplicationController
metadata:
  name: snapshot-rc
spec:
  replicas: 0
  # selector identifies the set of Pods that this
  # replicaController is responsible for managing
  selector:
    name: hawkular
    env: snapshot
  # podTemplate defines the 'cookie cutter' used for creating
  # new pods when necessary
  template:
    metadata:
      labels:
        # Important: these labels need to match the selector above
        # The api server enforces this constraint.
        name: hawkular
        env: snapshot
    spec:
      containers:
        - image: docker.io/hawkularqe/hawkular-services:latest
          name: hawkular
          ports:
          - containerPort: 8080
          env:
          - 
            name: TEST_MODE
            value: "true"
          -
            name: CASSANDRA_SERVICE
            value: "cassandra"
          -
            name: DB_TIMEOUT
            value: "480" 
          livenessProbe:
            httpGet:
              path: /hawkular/metrics/status
              port: 8080
            initialDelaySeconds: 360
