apiVersion: v1beta3
kind: ReplicationController
metadata:
  name: snapshot-rc
spec:
  replicas: 0
  # selector identifies the set of Pods that this
  # replicaController is responsible for managing
  selector:
    name: hawkular
    env: snapshot
  # podTemplate defines the 'cookie cutter' used for creating
  # new pods when necessary
  template:
    metadata:
      labels:
        # Important: these labels need to match the selector above
        # The api server enforces this constraint.
        name: hawkular
        env: snapshot
    spec:
      containers:
        - name: hawkular
          image: hawkular/hawkular:latest
          env:
            - name: TEST_MODE
              value: "true"
            - name: CASSANDRA_NODES
              value: 127.0.0.1
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            # length of time to wait for a pod to initialize
            # after pod startup, before applying health checking
            initialDelaySeconds: 480
            timeoutSeconds: 10
        - name: cassandra
          image: cassandra:2.2
          command:
            - bash
            - "-c"
            - "sed -i 's/^start_rpc.*$/start_rpc: true/' /etc/cassandra/cassandra.yaml; /docker-entrypoint.sh -f" 
          env:
            - name: CASSANDRA_LISTEN_ADDRESS
              value: 127.0.0.1
