apiVersion: v1beta3
kind: Service
metadata:
  labels:
    name: hawkulartest
    env: uismoke1
  name: hawkular-ui-test
spec:
  ports:
    - port: 18082
      targetPort: 80
  selector:
    name: hawkulartest
    env: uismoke1
  publicIPs:
    - 172.18.17.27
