apiVersion: v1beta3
kind: ReplicationController
metadata:
  name: ui-test-ctl1
spec:
  replicas: 1
  selector:
    name: hawkulartest
    env: uismoke1
  # podTemplate defines the 'cookie cutter' used for creating
  # new pods when necessary
  template:
    metadata:
      labels:
        # Important: these labels need to match the selector above
        # The api server enforces this constraint.
        name: hawkulartest
        env: uismoke1
    spec:
      containers:
        - name: uismoke1
          image: hawkularqe/ui-test:latest
          resources:
            limits:
              cpu: 1
          env:
            - name: WAIT_TRIES
              value: "10"
            - name: HAWKULAR_ENDPOINT
              value: $HAWKULAR_ENDPOINT_VALUE
            - name: AUTH_KEY
              value: $AUTH_KEY_VALUE
          volumeMounts:
            - mountPath: /opt/hawkular-ui-test/target/surefire-reports
              name: "reports"
        - name: webserver
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 1
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: "reports"
      volumes:
        - name: "reports"
          source:
            emptyDir:
                medium: 
