apiVersion: v1
kind: Service
metadata:
  labels:
    name: miq
    env: master
  name: manageiq
spec:
  type: "NodePort"
  ports:
    - name: "http"
      port: 80
      targetPort: 80
      nodePort: 31000
    - name: "https"
      port: 443
      targetPort: 443
      nodePort: 31443
  selector:
    name: miq
    env: master
