apiVersion: v1
kind: ReplicationController
metadata:
  name: miq-rc
spec:
  replicas: 1
  # selector identifies the set of Pods that this
  # replicaController is responsible for managing
  selector:
    name: miq
    env: master
  # podTemplate defines the 'cookie cutter' used for creating
  # new pods when necessary
  template:
    metadata:
      labels:
        # Important: these labels need to match the selector above
        # The api server enforces this constraint.
        name: miq
        env: master
    spec:
      containers:
        - name: manageiq
          image: docker.io/manageiq/manageiq
          ports:
            - containerPort: 80
            - containerPort: 443
          securityContext:
            privileged: true
          livenessProbe:
            httpGet:
              path: /
              port: 80
            # length of time to wait for a pod to initialize
            # after pod startup, before applying health checking
            initialDelaySeconds: 1200
            timeoutSeconds: 10
